language: java
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
before_install:
  # Use wrapper script to install fixed maven version
  - mvn -N io.takari:maven:wrapper -Dmaven=3.3.9
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw verify
notifications:
  slack:
    rooms:
      # Sends build status updates for molgenis/molgenis repo to #pr-platform channel on molgenis-dev slack
      secure: blnxfapt6aAdRDjNvy2Ykp3yPxhRqo0srfz9MI2obKGXFOO2ee+AF0TNosmz9aZG0J3u4e3YI+z9BvjcNMvTzzPCjiLiC3MSbtB9w0SHwhg6q7s1ehVoYKqB22++8S6GEYy5FgBpBLQ+jXEnwiglHfKLowJjvQS8s2NBMhAwEqY=
after_success:
  - .travis/sonar.sh
  - bash <(curl -s https://codecov.io/bash)
